title: Jan Joshua C. Aus # your name (or website title) here
logo: "assets/img/portfolio_pic.jpg?raw=True" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  An aspiring Data Scientist and AI/ML Engineer
  <br><br>
  Email: <a href="mailto:ausjanjoshua0@gmail.com">ausjanjoshua0@gmail.com</a>
  <br><br>
  <a href="https://linktr.ee/janjoshuaaus">Let's connect</a> 
  
theme: jekyll-theme-minimal
