title: Jan Joshua Aus
logo: assets/img/portfolio_pic.jpg
description: >
<br>
A B.S. Computer Science graduate of University of the East - Caloocan and an aspiring Data Scientist and AI/ML Engineer with experience on working with Computer Vision, Natural Language Processing, and Machine Learning. I am passionate about learning new technologies and applying them to solve real-world problems.
<br><br>
<p>Email: <a href="mailto:ausjanjoshua0@gmail.com">ausjanjoshua0@gmail.com</a></p>
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
